# CloudSITLSIM Configuration File

# Application settings
app:
  name: "CloudSITLSIM"
  version: "1.0.0"
  debug: false
  host: "0.0.0.0"
  port: 5000
  secret_key: "your-secret-key-change-this"

# PX4 settings
px4:
  path: "sitl_engines/px4/PX4-Autopilot"
  build_path: "sitl_engines/px4/PX4-Autopilot/build/px4_sitl_default"
  gazebo_world: "default"
  max_instances: 10

# MAVLink settings
mavlink:
  port_range:
    start: 14550
    end: 14600
  router_timeout: 5760
  external_interface: "0.0.0.0"

# Logging configuration
logging:
  level: "INFO"
  file: "logs/cloudsitlsim.log"
  max_size: "10MB"
  backup_count: 5

# Database settings
database:
  url: "sqlite:///instance/cloudsitlsim.db"
  echo: false

# Security settings
security:
  enable_auth: false
  admin_users: []
  session_timeout: 3600

# Resource limits
resources:
  max_cpu_percent: 80
  max_memory_mb: 2048
  cleanup_interval: 300

# Aircraft configurations
aircraft:
  default_types:
    - name: "iris"
      description: "Iris Quadcopter"
      gazebo_model: "iris"
      px4_model: "iris"
      autostart_id: "4001"
    
    - name: "x500"
      description: "X500 Quadcopter"
      gazebo_model: "x500"
      px4_model: "x500"
      autostart_id: "4001"
    
    - name: "solo"
      description: "3DR Solo Quadcopter"
      gazebo_model: "solo"
      px4_model: "solo"
      autostart_id: "4001"
    
    - name: "typhoon_h480"
      description: "Typhoon H480 Hexacopter"
      gazebo_model: "typhoon_h480"
      px4_model: "typhoon_h480"
      autostart_id: "4001"
    
    - name: "plane"
      description: "Generic Fixed-wing Aircraft"
      gazebo_model: "plane"
      px4_model: "plane"
      autostart_id: "2100"
    
    - name: "rover"
      description: "Generic Ground Rover"
      gazebo_model: "rover"
      px4_model: "rover"
      autostart_id: "50000"
    
    - name: "boat"
      description: "Generic Boat"
      gazebo_model: "boat"
      px4_model: "boat"
      autostart_id: "50001"

# Web interface settings
web:
  title: "CloudSITLSIM"
  refresh_interval: 5000
  enable_telemetry: true
  max_telemetry_points: 1000
