# CloudSITLSIM Configuration File

# Application settings
app:
  name: "CloudSITLSIM"
  version: "1.0.0"
  debug: false
  host: "0.0.0.0"
  port: 5000
  secret_key: "your-secret-key-change-this"

# PX4 settings
px4:
  path: "sitl_engines/px4/PX4-Autopilot"
  build_path: "sitl_engines/px4/PX4-Autopilot/build/px4_sitl_default"
  gazebo_world: "default"
  max_instances: 10

# MAVLink settings
mavlink:
  port_range:
    start: 14550
    end: 14600
  router_timeout: 5760
  external_interface: "0.0.0.0"

# Logging configuration
logging:
  level: "INFO"
  file: "logs/cloudsitlsim.log"
  max_size: "10MB"
  backup_count: 5

# Database settings
database:
  url: "sqlite:///instance/cloudsitlsim.db"
  echo: false

# Security settings
security:
  enable_auth: false
  admin_users: []
  session_timeout: 3600

# Resource limits
resources:
  max_cpu_percent: 80
  max_memory_mb: 2048
  cleanup_interval: 300

# Aircraft configurations - PX4 SITL with Gazebo (Headless Mode)
aircraft:
  default_types:
    # Quadrotor Aircraft
    - name: "x500"
      description: "X500 Quadrotor"
      gazebo_target: "gazebo"
      autostart_id: "4001"
    
    # VTOL Aircraft
    - name: "standard_vtol"
      description: "Standard VTOL"
      gazebo_target: "gazebo"
      autostart_id: "4004"
    
    - name: "quadtailsitter"
      description: "Quad Tailsitter VTOL"
      gazebo_target: "gazebo"
      autostart_id: "4018"
    
    - name: "tiltrotor"
      description: "Tiltrotor VTOL"
      gazebo_target: "gazebo"
      autostart_id: "4020"
    
    # Fixed-wing Aircraft
    - name: "rc_cessna"
      description: "RC Cessna Plane"
      gazebo_target: "gazebo"
      autostart_id: "4003"
    
    - name: "advanced_plane"
      description: "Advanced Plane"
      gazebo_target: "gazebo"
      autostart_id: "4008"
    
    # Ground Vehicles
    - name: "rover_differential"
      description: "Differential Rover"
      gazebo_target: "gazebo"
      autostart_id: "50000"
    
    - name: "rover_ackermann"
      description: "Ackermann Rover"
      gazebo_target: "gazebo"
      autostart_id: "51000"
    
    - name: "rover_mecanum"
      description: "Mecanum Rover"
      gazebo_target: "gazebo"
      autostart_id: "52000"

# Web interface settings
web:
  title: "CloudSITLSIM"
  refresh_interval: 5000
  enable_telemetry: true
  max_telemetry_points: 1000
